# NumPy

In [28]:
# 데이터 관리는 무조건 numpy! (리스트로 쓰는 것보다 훨씬 효율적이고 용량이 적게 다뤄짐!)

import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

# ndarray 객체 (가로세로가 똑같은 수학의 '행렬 구조'로 만들어야 함!)
# n차원 지원
# array함수의 리스트!
# ndarray는 가로세로를 정형화 구조로 만들어 버리니까 속도도 빠르다. (cpu에 특화!)
# 무조건 2차원 배열, 누적시키면 3차원, 4차원 됨(누적은 for문을 돌리면 된다.)
# 1차원 벡터가 누적되면, 2차원이고, 그게 누적되면 3차원, 4차원
# 누적은 for문을 활용하면 된다.

array([0, 1, 2, 3, 4, 5])

In [4]:
data2 = [0, 1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2


# ndarray가 시작되면 R에서 다룬 벡터 array와 비슷! 
# 파이썬의 기존 구조는 수학 구조에는 사실 매우 좋은 것은 아니다. 수학에는 정형화된 구조가 좋다. 

array([ 0. ,  1. ,  5. ,  4. , 12. ,  0.5])

In [5]:
a1.dtype

dtype('int32')

In [6]:
a2.dtype

dtype('float64')

In [7]:
# 2차원

np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
import numpy as np

b1 = np.arange(12), reshape(4, 3)
b1.shape
b1

NameError: name 'reshape' is not defined

In [11]:
np.eye(3)

# 대각선에 해당하는 값들을 1로 만들어 준다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [14]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

# 형변환 전에는 실수형 저장이라, 10.0 으로 저장! 
# 형변환 후에는 정수형!

array([10, 21,  0,  4,  5])

In [15]:
num_f1.dtype

dtype('float64')

In [19]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [20]:
arr1 + arr2

array([11, 22, 33, 44])

In [21]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [22]:
arr2 * 2

array([2, 4, 6, 8])

In [23]:
arr2 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [24]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [25]:
arr1 / arr2

array([10., 10., 10., 10.])

In [26]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [27]:
arr1 > 20

array([False, False,  True,  True])

# 통계를 위한 연산

NumPy에는 배열의 합, 평균, 표준 편차, 분산, 최솟값과 최댓값, 누적 합과 누적 곱 등
주로 통계에서 많이 이용하는 메서드가 있다.
이 메서드는 각각

sum(), mean(), std(), var(), min(), max(), cumsum(), cumprod()

In [18]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [29]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [31]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [32]:
[arr3.min(), arr3.max()]

[0, 4]

In [33]:
arr4 = np.arange(1, 5)
arr4

array([1, 2, 3, 4])

In [34]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [35]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

ndarray 객체면 객체 안에 모든 기능들이 많이 된다. 
일단 nparray 실행만 하면 나머지는 알아서 명령만 하면 입력이 되는 것들이 많다.

## "내적"의 의미

행렬을 위한 값들을 다 곱하고 그 합!
(행렬 구하는 것과 똑같다.)

In [37]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [38]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [39]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [40]:
np.dot(A, B)

array([[0, 1],
       [6, 7]])

## 전치 행렬

'행'과 '열'을 바꾼다.

모든 데이터는 NumPy로 하면 다 받아주는데, List는 안 바꿔줄 때가 많음.
Numpy로 바꾸는 함수식 (np.array([*]))이 가장 많이 쓰인다!

In [42]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [44]:
test = [[0, 10], [20, 30], [40, 50]]  # 3행 2열 순수 List로 만듦
# test2 = test.reshape(3, 2)
test[0], [1]

([0, 10], [1])

In [45]:
test2 = np.array(test)  # 일반 list 구조 test는 nd.array화 하면  순서를 연달아 [] 안에 넣는 것이 가능~!
test2[0, 1]

10

## np.arange

In [53]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [54]:
a2[0, 2]

30

In [55]:
a2[2, 2]

90

In [56]:
a2[1]

array([40, 50, 60])

In [57]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 90]])

In [58]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 90]])

### 11장: 233쪽

In [59]:
a2[[0, 2], [0, 1]]  # 2차원 (a2의 값을 여러 개 불러오는 인덱스)

array([10, 80])

In [60]:
# a2[0, 0]

10

In [61]:
# a2[2, 1]

80

In [63]:
# a2[[0, 0], [2, 1]]    # [0, 2], [0, 1] (보여지는 것과 다른 값을 불러옴!)

array([30, 20])

In [62]:
a2[[0, 2], [0, 1]]

array([10, 80])

### ndarray의 가장 큰 장점 중 하나!

In [64]:
a = np.array([1, 2, 3, 4, 5, 6])

In [66]:
a > 3         # 조건 연산지만 넣어도 모든 요소에 대해서 모든 요소가 조건을 만족하는지 나타내준다.

array([False, False, False,  True,  True,  True])

In [67]:
a[a > 3]     # 조건에 부합하는 값을 보여준다. ** filter 함수 적용할 필요 없다!  ** 진짜 많이 쓰인다!

array([4, 5, 6])

In [68]:
a[(a % 2) == 0]  

array([2, 4, 6])

### 배열 슬라이싱

In [69]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [70]:
b1[:3]

array([ 0, 10, 20])

In [71]:
b1[2:]

array([20, 30, 40, 50])

In [72]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [73]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [81]:
# 2차원 배열 슬라이싱

b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [82]:
b2[1:3, 1:3]

array([[50, 60],
       [80, 90]])

In [83]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [84]:
b2[1][0:2]

array([40, 50])

In [87]:
b2[0:2, 1:3] = np.array([[25, 35], [55, 65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])

## NumPy는 시간 구조(Serial)에 대해 해결하지 못한다
## 해결책: Pandas